export const resultadoAlgo3 = [
  {
    containerID: 2,
    algorithmPackingResults: [
      {
        algorithmID: 1,
        algorithmName: "EB-AFIT",
        isCompletePack: false,
        packedItems: [
          {
            id: 3,
            isPacked: true,
            dim1: 5,
            dim2: 5,
            dim3: 5,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 5,
            packDimY: 5,
            packDimZ: 5,
            volume: 125,
          },
          {
            id: 3,
            isPacked: true,
            dim1: 5,
            dim2: 5,
            dim3: 5,
            coordX: 5,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 5,
            packDimY: 5,
            packDimZ: 5,
            volume: 125,
          },
          {
            id: 3,
            isPacked: true,
            dim1: 5,
            dim2: 5,
            dim3: 5,
            coordX: 0,
            coordY: 0,
            coordZ: 5,
            quantity: 1,
            packDimX: 5,
            packDimY: 5,
            packDimZ: 5,
            volume: 125,
          },
          {
            id: 3,
            isPacked: true,
            dim1: 5,
            dim2: 5,
            dim3: 5,
            coordX: 5,
            coordY: 0,
            coordZ: 5,
            quantity: 1,
            packDimX: 5,
            packDimY: 5,
            packDimZ: 5,
            volume: 125,
          },
          {
            id: 3,
            isPacked: true,
            dim1: 5,
            dim2: 5,
            dim3: 5,
            coordX: 0,
            coordY: 5,
            coordZ: 0,
            quantity: 1,
            packDimX: 5,
            packDimY: 5,
            packDimZ: 5,
            volume: 125,
          },
          {
            id: 2,
            isPacked: true,
            dim1: 3,
            dim2: 3,
            dim3: 3,
            coordX: 5,
            coordY: 5,
            coordZ: 0,
            quantity: 1,
            packDimX: 3,
            packDimY: 3,
            packDimZ: 3,
            volume: 27,
          },
          {
            id: 2,
            isPacked: true,
            dim1: 3,
            dim2: 3,
            dim3: 3,
            coordX: 5,
            coordY: 5,
            coordZ: 3,
            quantity: 1,
            packDimX: 3,
            packDimY: 3,
            packDimZ: 3,
            volume: 27,
          },
          {
            id: 2,
            isPacked: true,
            dim1: 3,
            dim2: 3,
            dim3: 3,
            coordX: 2,
            coordY: 5,
            coordZ: 5,
            quantity: 1,
            packDimX: 3,
            packDimY: 3,
            packDimZ: 3,
            volume: 27,
          },
        ],
        packTimeInMilliseconds: 0,
        percentContainerVolumePacked: 70.6,
        percentItemVolumePacked: 22.72,
        unpackedItems: [
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 7,
            packDimY: 7,
            packDimZ: 7,
            volume: 343,
          },
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 0,
            packDimY: 0,
            packDimZ: 0,
            volume: 343,
          },
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 0,
            packDimY: 0,
            packDimZ: 0,
            volume: 343,
          },
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 0,
            packDimY: 0,
            packDimZ: 0,
            volume: 343,
          },
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 0,
            packDimY: 0,
            packDimZ: 0,
            volume: 343,
          },
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 0,
            packDimY: 0,
            packDimZ: 0,
            volume: 343,
          },
          {
            id: 1,
            isPacked: false,
            dim1: 7,
            dim2: 7,
            dim3: 7,
            coordX: 0,
            coordY: 0,
            coordZ: 0,
            quantity: 1,
            packDimX: 0,
            packDimY: 0,
            packDimZ: 0,
            volume: 343,
          },
        ],
      },
    ],
  },
];
